name: debugger-action
on: 
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: keepalive
       run: touch /tmp/keepalive
     
     - name: Setup Debug Session
       uses: csexton/debugger-action@master
